### PR TITLE
build_image: Fix image type conditional

### PR DESCRIPTION
**Pull request by glevand**
@mjg59 I think this is what was intended.

### CODE REVIEW

**Comment by mischief** [comment]
rebase this please

**Comment by marineam** [comment]
Did this slightly differently in https://github.com/coreos/scripts/issues/532 which leaves sbsign enabled. I figure it is worth while to make sure that keeps working :)

**Comment by glevand** [comment]
@marineam It seems https://github.com/coreos/scripts/pull/532 does something different.  Even with that applied, we are still using PROD_IMAGE incorrectly in build_image_util.sh, which is what this PR tries to fix.

**Comment by marineam** [comment]
Oh, I see. yeah, so this is wrong when building dev and prod at the same time. Seems like a refactoring or adding an argument is in order but this approach will work for now.

**Pull request closed without merging**
