### PR TITLE
disk_layout: switch to ext4 as the default root filesystem.

### PR DESCRIPTION
**Pull request by marineam**
A brief summary: https://lwn.net/Articles/627232/ ;-)

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by infowolfe** [comment]
Line 282 of coreos-install needs to be updated in 561.0.0 to reflect the fact that you're no longer mounting btrfs.

```diff
--- coreos-install.orig	2015-01-23 20:57:33.000000000 -0600
+++ coreos-install	2015-01-23 20:57:42.000000000 -0600
@@ -279,7 +279,7 @@

     echo "Installing cloud-config..."
     mkdir -p "${WORKDIR}/rootfs"
-    mount -t btrfs -o subvol=root "${ROOT_DEV}" "${WORKDIR}/rootfs"
+    mount "${ROOT_DEV}" "${WORKDIR}/rootfs"
     trap "umount '${WORKDIR}/rootfs' && rm -rf '${WORKDIR}'" EXIT

     mkdir -p "${WORKDIR}/rootfs/var/lib/coreos-install"
````

**Comment by xueshanf** [comment]
We are using a dedicated /var/lib/docker volume by following this instruction:

[use-attached-storage-for-docker](https://coreos.com/docs/cluster-management/setup/mounting-storage/#use-attached-storage-for-docker)

Should we switch this volume to ext4+overlyFS and how?

**Comment by xuwang** [comment]
@xueshanf you can put the following units in cloud-config. Change the DEV to match your device name.

```
# /etc/systemd/system/format-disk.service
[Unit]
Description=Formats the disk drive
[Service]
Type=oneshot
RemainAfterExit=yes
Environment="LABEL=var-lib-docker"
Environment="DEV=/dev/xvdb"
# Do not wipe file system if it's already being used.
ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then  wipefs -a -f $DEV && mkfs.ext4 -F -L $LABEL $DEV && echo wiped; fi"
```
```
# /etc/systemd/system/var-lib-docker.mount
[Unit]
Description=Mount disk to /var/lib/docker
Requires=format-disk.service
After=format-disk.service
Before=docker.service
[Mount]
What=/dev/xvdb
Where=/var/lib/docker
Type=ext4
```

**Comment by xueshanf** [comment]
@xuwang tested and it worked! Thank you!

**Pull request merged**
