### PR TITLE
Fixups for jenkins

### PR DESCRIPTION
**Pull request by glevand**
For developer builds we weren't setting COREOS_BUILD_ID and PORTAGE_BINHOST correctly.  Also, remove the old jenkins jobs that have been replaced by https://github.com/coreos/jenkins-os.

### CODE REVIEW

**Comment by glevand** [comment]
Rebased to latest.

**Comment by glevand** [comment]
Rebased to latest.

**Comment by glevand** [comment]
- Changed PORTAGE_BINHOST to also use COREOS_VERSION for board packages.
- Also remove COREOS_BUILD_ID quotes when writing manifest/version.txt.
- Added a patch `load_environment_var: Strip double quotes` to handle legacy version.txt.

**Comment by glevand** [comment]
Rebased to latest.

**Comment by glevand** [comment]
Dropped patches `version.txt: Remove quotes around COREOS_BUILD_ID` and `PORTAGE_BINHOST: Use COREOS_VERSION`.

I'll try the `--getbinpkgver` in the jenkins scripts and adjust those as needed.

**Comment by glevand** [comment]
@marineam I changed the setting of COREOS_BUILD_ID so it is set in order of
preference, to

- A value set in the environment.
- A value provided in manifest's version.txt.
- A fall back value of the current time-date.

Will this work?

**Comment by marineam** [comment]
Yup, that works!

**Pull request merged**
