### PR TITLE
disk_util: use the dummy disk UUID

### PR DESCRIPTION
**Pull request by crawford**
Depends on https://github.com/coreos/seismograph/pull/32.

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by marineam** [comment]
should this wait until there is a job in the initrd to initialize it on first boot?

**Comment by crawford** [comment]
@marineam yes, I should have called that out.

**Comment by crawford** [comment]
Depends on https://github.com/coreos/bootengine/pull/49.

**Pull request merged**
