### PR TITLE
*: don't hardcode path to bash

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by bgilbert** [comment]
This only changes a small subset of the scripts that hardcode /bin, so not really `*`.  What problem is this solving?

**Comment by euank** [comment]
No problems here, only solutions



@crawford shouldn't that path be fine within the sdk chroot though, where we can make such assumptions?

**Comment by bgilbert** [comment]
I see.  @crawford, if you proceed with this change, please add an explanation to the commit message.  Otherwise this will be incomprehensible to anyone looking at the commit history.

**Comment by crawford** [comment]
@euank these scripts are called outside of the SDK. The others are fine assuming the bash location.

**Pull request merged**
