### PR TITLE
build_jobs: update manifest-builds location

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by marineam** [comment]
Is the https url usable? Or does everything need to convert to ssh?

**Comment by marineam** [comment]
Nm, you changed it :)

**Comment by marineam** [comment]
Changing the manifest url to ssh:// causes all github repos to be fetched over ssh:// (the urls in the XML manifest are relative to the manifest url) so please update the comments on all the jobs to note that ssh read-only access is required to all repos.

**Comment by crawford** [comment]
Going to do this on the new Jenkins instead.

**Pull request closed without merging**
